### PR TITLE
Strengthen the publicExponent

### PR DESCRIPTION
**Pull request by jas-**
Using a random value for the publicExponent of window.crypto.subtle.generateKey() will help protect against inadequate padding as well as strengthen the key generation.

Ref: http://crypto.stackexchange.com/questions/3110/impacts-of-not-using-rsa-exponent-of-65537

### CODE REVIEW

**Comment by dlajarretie** [comment]
:no_entry_sign:  :shipit:

**Comment by dlajarretie** [comment]
Your code creates a 65536-bytes long array filled with random values ; According to the link you provided, the value 65537 (as it is currently) is way enough secure to be used as public exponent.

**Comment by agix** [comment]
I'm not sure if you or I don't understand what to pass in publicExponent.
It should be a BigInteger http://www.w3.org/TR/WebCryptoAPI/#dfn-BigInteger.

> The BigInteger typedef is a Uint8Array that holds an arbitrary magnitude unsigned integer in big-endian order.

So 0x010001 == 65537.

I don't think you should pass a 65537 bytes long array.

according to http://src.chromium.org/viewvc/blink/trunk/LayoutTests/crypto/subtle/rsa-oaep/generate-non-extractable-key.html?revision=190912

and https://github.com/diafygi/webcrypto-examples#rsa-oaep---generatekey

**Comment by jas-** [comment]
You are right, I missed the part of the `BigInteger` documentation regarding the unsigned integer acceptable value:

> Values read from the API SHALL have minimal typed array length (that is, at most 7 leading zero bits, except the value 0 which shall have length 8 bits). The API SHALL accept values with any number of leading zero bits, including the empty array, which represents zero.

**Pull request closed without merging**
